config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions do

    member do
      post :upvote
      post :downvote
    end

    resources :answers do
      member do
        post :upvote
        post :downvote
      end
    end

  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    this_question = Question.find(params[:question_id])
    answer = Answer.new(answer_params)
    this_question.answers << answer

    redirect_to question_path(this_question)
  end

  def upvote
    answer = Answer.find(params[:id])
    question = Question.find(answer.question_id)
    answer.upvote
    redirect_to question
  end

  def downvote
    answer = Answer.find(params[:id])
    question = Question.find(answer.question_id)
    answer.downvote
    redirect_to question
  end

private
  def answer_params
    params.require(:answer).permit(:title, :content, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

end

app/controllers/questions_controller.rb
require 'httparty'
require 'json'

class QuestionsController < ApplicationController
  # include HTTParty

  def index
    @questions = Question.all.sort_by(&:created_at).reverse
    quote = HTTParty.get("https://api.github.com/zen",
      headers: {"User-Agent" => "philril", "access_token" => ENV['GITHUB_API']},
    )

    canned_response = [
      "Shitty quote",
      "Some quote stuff",
      "Some super inspirational quote stuff",
      "Blah blah blah"
    ]

    if quote.headers['status'] == "403 Forbidden"
      @quote = "'#{canned_response.shuffle.pop}'"
    else
      @quote = "'#{quote.body}'"
    end

  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html {redirect_to @question}
        format.js {}
        format.json {render json: @question, status :created, location: @question}
      else
        format.html {render action: "new"}
        format.json {render json @question.errors}
      end
      end

    @question.save
    redirect_to questions_path
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def upvote
    @question = Question.find(params[:id])
    @question.upvote
    redirect_to root_path
  end

  def downvote
    @question = Question.find(params[:id])
    @question.downvote
    redirect_to root_path
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Question Deleted"
    redirect_to root_path
  end

private
  def question_params
    params.require(:question).permit(:title, :content, :votes)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/question/_form.html.erb
<%= form_for @questions do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/question/index.html.erb
<h1>Question#index</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <p>New Question:</p>
  <%= render 'form' %>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.content %></td>
    </tr>
  <% end %>
</table>

app/views/question/show.html.erb
<h1>Question#show</h1>
<p>Find me in app/views/question/show.html.erb</p>

<%= @question.title %>
<%= @question.content %>

app/views/questions/_answer_form.html.erb
<%= form_for :answer, url: question_answers_path(@question.id) do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :placeholder => "Title" %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, :placeholder => "Content"  %>
  </p>

  <p>
    <%= f.submit :placeholder => "Save Answer" %>
  </p>
<% end %>

app/views/questions/_question_form.html.erb
<%= form_for :question, url: questions_path, remote: true do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>

<p>Edit Question:</p>

<%= form_for (@question), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/index.html.erb
<h1>Questions#index</h1>

<h3>Quote of the day:</h3>
<h4><%= @quote %></h4>

<ul>
  <% @questions.each do |question| %>
    <li>
      <h2><%= link_to question.title, question %></h2>
      <p><%= question.content %></p>
      <h4><%= question.answers.count %> Answers, <%= question.votes %> votes</h4>
      <button><%= link_to "Upvote", upvote_question_path(question.id), method: :post %></button>
      <button><%= link_to "Downvote", downvote_question_path(question.id), method: :post %></button>
    </li>
  <% end %>
</ul>

<p>New Question:</p>
<%= render 'question_form' %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

<%= button_to 'Delete Question', question_path(@question),
  method: :delete,
  data: { confirm: 'Are you sure you want to delete this question and all associated answers?' } %>
<%= button_to 'Edit Question', edit_question_path(@question) %>



<h1><%= @question.title %></h1>
<p><%= @question.content %></p><br>
<p><%= @question.votes %> votes</p>

<h3><%= @question.answers.count %> Answers:</h3>
<p><% @question.answers.each do |answer| %></p>
  <ul>
    <li><h4><%= answer.title %></h4>
      <p><%= answer.content %></p>
      <p><%= answer.votes %> Votes</p>
      <%= button_to "Upvote", upvote_question_answer_path(answer.question, answer), method: :post %>
      <%= button_to "Downvote", downvote_question_answer_path(answer.question, answer), method: :post %>
    </li>
  </ul>
<% end %>



<h3>New Answer:</h3>
<%= render 'answer_form' %>

<%= link_to 'Back', root_path %>